# Generated by Django 4.2.27 on 2026-01-13 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito')], default='PIX', max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('external_id', models.CharField(help_text='ID do pagamento no Mercado Pago', max_length=255, unique=True, verbose_name='ID Externo (MP)')),
                ('preference_id', models.CharField(blank=True, help_text='ID da preferência criada no Mercado Pago', max_length=255, verbose_name='ID da Preferência')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('payment_details', models.JSONField(blank=True, default=dict, help_text='JSON com informações completas do Mercado Pago', verbose_name='Detalhes do Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='billing_pay_subscri_d33e55_idx'), models.Index(fields=['external_id'], name='billing_pay_externa_fdfe9a_idx'), models.Index(fields=['status', '-created_at'], name='billing_pay_status_bc3ae3_idx')],
            },
        ),
    ]
