# Generated by Django 4.2.27 on 2026-01-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CNH', 'CNH (Carteira Nacional de Habilitação)'), ('CERT_INSTRUTOR', 'Certificado de Instrutor'), ('DOC_VEICULO', 'Documento do Veículo'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(help_text='PDF, JPG ou PNG (máx 10MB)', upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Motivo da aprovação/rejeição', verbose_name='Observações')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketplace.instructorprofile', verbose_name='Instrutor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Documento de Instrutor',
                'verbose_name_plural': 'Documentos de Instrutores',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='verificatio_instruc_4a282b_idx'), models.Index(fields=['status', 'uploaded_at'], name='verificatio_status_74f923_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('object_type', models.CharField(max_length=50, verbose_name='Tipo de Objeto')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_user', 'created_at'], name='verificatio_actor_u_e2c0cf_idx'), models.Index(fields=['object_type', 'object_id'], name='verificatio_object__67a13b_idx')],
            },
        ),
    ]
