# Generated by Django 4.2.27 on 2026-01-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordocument',
            name='cnh_valid',
            field=models.BooleanField(blank=True, help_text='Número da CNH passou na validação', null=True, verbose_name='CNH Válida'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='cpf_valid',
            field=models.BooleanField(blank=True, help_text='CPF passou na validação', null=True, verbose_name='CPF Válido'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='extracted_cnh_number',
            field=models.CharField(blank=True, help_text='Número da CNH extraído via OCR', max_length=11, verbose_name='Número CNH Extraído'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='extracted_cpf',
            field=models.CharField(blank=True, help_text='CPF extraído via OCR', max_length=11, verbose_name='CPF Extraído'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='extracted_name',
            field=models.CharField(blank=True, help_text='Nome completo extraído via OCR', max_length=200, verbose_name='Nome Extraído'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='extracted_validity',
            field=models.DateField(blank=True, help_text='Data de validade extraída via OCR', null=True, verbose_name='Validade Extraída'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confiança da extração (0-100%)', max_digits=5, null=True, verbose_name='Confiança do OCR'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='validity_ok',
            field=models.BooleanField(blank=True, help_text='Documento está dentro da validade', null=True, verbose_name='Dentro da Validade'),
        ),
    ]
