# Generated by Django 4.2.27 on 2026-01-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0002_instructordocument_cnh_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordocument',
            name='face_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confiança da comparação facial (0-100%)', max_digits=5, null=True, verbose_name='Confiança da Comparação'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='face_match',
            field=models.BooleanField(blank=True, help_text='Selfie corresponde à foto do documento', null=True, verbose_name='Rosto Corresponde'),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='selfie',
            field=models.ImageField(blank=True, help_text='Foto do rosto para comparar com documento', null=True, upload_to='selfies/%Y/%m/', verbose_name='Selfie'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FAKE_PROFILE', 'Perfil Falso'), ('FAKE_DOCUMENT', 'Documento Falso'), ('SCAM', 'Golpe/Fraude'), ('HARASSMENT', 'Assédio'), ('NO_SHOW', 'Não compareceu à aula'), ('POOR_SERVICE', 'Serviço ruim'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Denúncia')),
                ('description', models.TextField(help_text='Detalhe o que aconteceu', verbose_name='Descrição')),
                ('evidence', models.FileField(blank=True, help_text='Screenshot, foto ou documento comprobatório', null=True, upload_to='reports/%Y/%m/', verbose_name='Evidência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('INVESTIGATING', 'Em Investigação'), ('RESOLVED', 'Resolvido'), ('DISMISSED', 'Arquivado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Investigação e decisão', verbose_name='Notas do Administrador')),
                ('action_taken', models.CharField(blank=True, choices=[('NONE', 'Nenhuma'), ('WARNING', 'Advertência'), ('SUSPENSION', 'Suspensão'), ('PERMANENT_BAN', 'Banimento Permanente')], max_length=20, verbose_name='Ação Tomada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL, verbose_name='Investigado por')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Denunciado')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported_user', 'status'], name='verificatio_reporte_5a95ac_idx'), models.Index(fields=['status', 'created_at'], name='verificatio_status_c621ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MULTIPLE_REJECTIONS', 'Múltiplas Rejeições'), ('RAPID_REGISTRATION', 'Cadastro Muito Rápido'), ('FAKE_DATA', 'Dados Falsos'), ('DUPLICATE_ACCOUNT', 'Conta Duplicada'), ('ABNORMAL_BEHAVIOR', 'Comportamento Anormal'), ('REPORTED_MULTIPLE', 'Múltiplas Denúncias')], max_length=30, verbose_name='Tipo de Atividade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10, verbose_name='Severidade')),
                ('auto_detected', models.BooleanField(default=True, help_text='Foi detectado pelo sistema ou reportado manualmente', verbose_name='Detectado Automaticamente')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade Suspeita',
                'verbose_name_plural': 'Atividades Suspeitas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reviewed'], name='verificatio_user_id_a1a250_idx'), models.Index(fields=['severity', 'created_at'], name='verificatio_severit_90d6cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNH', 'CNH'), ('CPF', 'CPF'), ('RG', 'RG'), ('PHONE', 'Telefone'), ('EMAIL', 'Email')], max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(help_text='Número sem formatação', max_length=50, verbose_name='Número do Documento')),
                ('reason', models.CharField(choices=[('FAKE', 'Documento Falso'), ('STOLEN', 'Documento Roubado'), ('DUPLICATED', 'Uso Duplicado'), ('FRAUD', 'Fraude Confirmada')], max_length=20, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, help_text='Detalhes sobre o bloqueio', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Blacklist ativo', verbose_name='Ativo')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração (deixe em branco para permanente)', null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Blacklist de Documento',
                'verbose_name_plural': 'Blacklist de Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'document_number', 'is_active'], name='verificatio_documen_be28c5_idx')],
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
