# Generated by Django 4.2.27 on 2026-02-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_instructordocument_face_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDocument',
            fields=[
            ],
            options={
                'verbose_name': '⏳ Documento Pendente',
                'verbose_name_plural': '⏳ Fila de Aprovação',
                'ordering': ['uploaded_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('verification.instructordocument',),
        ),
    ]
