# Generated by Django 4.2.27 on 2026-01-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('source', models.CharField(help_text='Ex: G1, UOL, Folha', max_length=200, verbose_name='Fonte')),
                ('source_url', models.URLField(verbose_name='URL da Fonte')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('summary', models.TextField(help_text='Breve descrição da notícia', verbose_name='Resumo')),
                ('content', models.TextField(blank=True, help_text='Conteúdo completo (opcional)', verbose_name='Conteúdo')),
                ('published_date', models.DateTimeField(verbose_name='Data de Publicação')),
                ('category', models.CharField(choices=[('legislacao', 'Legislação'), ('habilitacao', 'Habilitação'), ('multas', 'Multas e Infrações'), ('tecnologia', 'Tecnologia'), ('seguranca', 'Segurança no Trânsito'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='core_newsar_publish_75a99c_idx'), models.Index(fields=['category'], name='core_newsar_categor_82c61f_idx')],
            },
        ),
    ]
