# Generated by Django 4.2.27 on 2026-01-06 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCNH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Categoria A - Motos'), ('B', 'Categoria B - Carros'), ('C', 'Categoria C - Caminhões'), ('D', 'Categoria D - Ônibus'), ('E', 'Categoria E - Carretas')], max_length=1, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria CNH',
                'verbose_name_plural': 'Categorias CNH',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Cidade disponível no marketplace', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Descreva sua experiência', max_length=1000, verbose_name='Sobre mim')),
                ('neighborhoods_text', models.CharField(blank=True, help_text='Ex: Centro, Jardins, Vila Mariana', max_length=255, verbose_name='Bairros atendidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Gênero')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('years_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Anos de experiência')),
                ('has_own_car', models.BooleanField(default=False, verbose_name='Possui carro próprio')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo do carro')),
                ('available_morning', models.BooleanField(default=True, verbose_name='Disponível de manhã')),
                ('available_afternoon', models.BooleanField(default=True, verbose_name='Disponível à tarde')),
                ('available_evening', models.BooleanField(default=False, verbose_name='Disponível à noite')),
                ('base_price_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Valor aproximado (opcional)', max_digits=6, null=True, verbose_name='Preço base por hora')),
                ('price_notes', models.CharField(blank=True, help_text='Ex: Preço por pacote de 10 aulas', max_length=255, verbose_name='Observações sobre preço')),
                ('is_visible', models.BooleanField(default=True, help_text='Desmarque para pausar temporariamente seu perfil', verbose_name='Visível no marketplace')),
                ('is_verified', models.BooleanField(default=False, help_text='Instrutor com documentos aprovados', verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categories', models.ManyToManyField(blank=True, related_name='instructors', to='marketplace.categorycnh', verbose_name='Categorias que ensina')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='marketplace.city', verbose_name='Cidade Principal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Instrutor',
                'verbose_name_plural': 'Perfis de Instrutores',
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Sigla do Estado (ex: SP)', max_length=2, unique=True, verbose_name='UF')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='marketplace.state', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('preferred_schedule', models.CharField(blank=True, help_text='Ex: Manhã, Tarde, Noite', max_length=50, verbose_name='Horário preferido')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contatado'), ('CLOSED', 'Fechado'), ('SPAM', 'Spam')], default='NEW', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.city', verbose_name='Cidade')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_received', to='marketplace.instructorprofile', verbose_name='Instrutor')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_sent', to=settings.AUTH_USER_MODEL, verbose_name='Aluno (usuário)')),
            ],
            options={
                'verbose_name': 'Lead/Contato',
                'verbose_name_plural': 'Leads/Contatos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='marketplace_instruc_a7c82b_idx'), models.Index(fields=['created_at'], name='marketplace_created_bb040f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['city', 'is_visible', 'is_verified'], name='marketplace_city_id_06a90a_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['gender'], name='marketplace_gender_fb39f6_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['has_own_car'], name='marketplace_has_own_c32eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'name'], name='marketplace_state_i_a15f93_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='marketplace_slug_dd9f37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
