# Generated by Django 4.2.27 on 2026-01-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_instructorprofile_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude da capital do estado', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude da capital do estado', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
