# Generated by Django 4.2.27 on 2026-01-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_state_latitude_state_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID original do lead', max_length=100, unique=True, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('category', models.CharField(help_text='Categoria desejada: A, B, AB, etc.', max_length=3, verbose_name='Categoria CNH')),
                ('has_theory', models.BooleanField(default=False, help_text='Já possui parte teórica', verbose_name='Tem teoria')),
                ('accept_marketing', models.BooleanField(default=False, verbose_name='Aceita marketing')),
                ('accept_whatsapp', models.BooleanField(default=False, verbose_name='Aceita WhatsApp')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Aceitou termos')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Foi contatado')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do contato')),
                ('notified_about_instructor', models.BooleanField(default=False, help_text='Já foi notificado que há instrutor disponível no estado', verbose_name='Notificado sobre instrutor')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da notificação')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais do CSV', verbose_name='Metadados')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_leads', to='marketplace.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Lead de Aluno',
                'verbose_name_plural': 'Leads de Alunos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'notified_about_instructor'], name='marketplace_state_i_4b9704_idx'), models.Index(fields=['is_contacted'], name='marketplace_is_cont_8161d1_idx'), models.Index(fields=['created_at'], name='marketplace_created_47d321_idx')],
            },
        ),
    ]
