# Generated by Django 4.2.27 on 2026-01-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_studentlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='is_trial_active',
            field=models.BooleanField(default=False, help_text='Instrutor está no período de trial gratuito', verbose_name='Trial Ativo'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_blocked_notified',
            field=models.BooleanField(default=False, help_text='E-mail de bloqueio enviado', verbose_name='Notificado ao Bloquear'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='Data em que o trial de 14 dias termina', null=True, verbose_name='Data de Fim do Trial'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_expiration_notified_1d',
            field=models.BooleanField(default=False, help_text='E-mail de aviso 1 dia antes enviado', verbose_name='Notificado 1 dia antes'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_expiration_notified_3d',
            field=models.BooleanField(default=False, help_text='E-mail de aviso 3 dias antes enviado', verbose_name='Notificado 3 dias antes'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_expiration_notified_7d',
            field=models.BooleanField(default=False, help_text='E-mail de aviso 7 dias antes enviado', verbose_name='Notificado 7 dias antes'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='Data em que o trial de 14 dias começou', null=True, verbose_name='Data de Início do Trial'),
        ),
    ]
