# Generated by Django 4.2.27 on 2026-01-12 23:34

from django.db import migrations, models
import django.db.models.deletion


def convert_city_to_fk(apps, schema_editor):
    """
    Convert old city CharField to new city ForeignKey
    Since we're starting fresh with new student registrations,
    we can simply clear old data that doesn't have proper City FK
    """
    StudentLead = apps.get_model('marketplace', 'StudentLead')
    # Clear all existing student leads as they're from old CSV import
    # New students will register through the form with proper City FK
    StudentLead.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_migrate_city_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlead',
            name='accept_marketing',
        ),
        migrations.RemoveField(
            model_name='studentlead',
            name='category',
        ),
        migrations.AddField(
            model_name='studentlead',
            name='accept_email',
            field=models.BooleanField(default=True, help_text='Aceita receber mensagens via email', verbose_name='Aceita Email'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='categories',
            field=models.ManyToManyField(help_text='Categorias de CNH que deseja obter', related_name='student_leads', to='marketplace.categorycnh', verbose_name='Categorias Desejadas'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do aluno (opcional)', null=True, upload_to='students/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='accept_terms',
            field=models.BooleanField(default=False, help_text='Aceitou os termos de uso', verbose_name='Aceitou Termos'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='accept_whatsapp',
            field=models.BooleanField(default=True, help_text='Aceita receber mensagens via WhatsApp', verbose_name='Aceita WhatsApp'),
        ),
        # Run data conversion before changing field type
        migrations.RunPython(convert_city_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentlead',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_leads', to='marketplace.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID original do lead', max_length=100, null=True, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='has_theory',
            field=models.BooleanField(default=False, help_text='Já concluiu a parte teórica', verbose_name='Concluiu Parte Teórica'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
    ]
