# Generated by Django 4.2.27 on 2026-01-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_instructorprofile_is_trial_active_and_more'),
        ('marketplace', '0007_remove_studentlead_accept_marketing_and_more'),
    ]

    operations = [
    ]
