# Generated by Django 4.2.27 on 2026-01-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_scheduling_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='marketplace_instruc_495b85_idx',
            old_name='marketplace_instru_appt_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='marketplace_student_a50951_idx',
            old_name='marketplace_student_appt_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='marketplace_is_conf_db4863_idx',
            old_name='marketplace_appt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='instructoravailability',
            new_name='marketplace_instruc_4410fe_idx',
            old_name='marketplace_instru_weekday_idx',
        ),
    ]
