# Generated by Django 4.2.27 on 2026-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_rename_marketplace_instru_appt_idx_marketplace_instruc_495b85_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(db_index=True, help_text='Formato: cidade_normalizada|UF', max_length=200, unique=True, verbose_name='Chave Cidade')),
                ('city_name', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state_code', models.CharField(max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('provider', models.CharField(blank=True, help_text='API de geocoding usada (nominatim, google, manual, etc.)', max_length=50, verbose_name='Provedor')),
                ('geocoded', models.BooleanField(default=False, verbose_name='Geocodificado')),
                ('failed', models.BooleanField(default=False, help_text='Geocoding falhou', verbose_name='Falhou')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cache de Geocoding',
                'verbose_name_plural': 'Cache de Geocoding',
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['city_key'], name='marketplace_city_ke_feddbd_idx'),
                    models.Index(fields=['state_code', 'city_name'], name='marketplace_state_c_83de62_idx'),
                    models.Index(fields=['geocoded'], name='marketplace_geocode_f90003_idx'),
                ],
            },
        ),
    ]
