# Generated by Django 4.2.27 on 2026-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_instructorprofile_verification_denied'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instructorprofile',
            name='marketplace_pioneer_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='marketplace_ibge_id_e611f8_idx',
            old_name='marketplace_ibge_id_city_idx',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, help_text='Número de vezes que o perfil foi visualizado', verbose_name='Visualizações do Perfil'),
        ),
    ]
