# Generated by Django 4.2.27 on 2026-01-06 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+5511999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Número do WhatsApp (pode ser igual ao telefone)', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+5511999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('role', models.CharField(choices=[('STUDENT', 'Aluno'), ('INSTRUCTOR', 'Instrutor'), ('ADMIN_SUPPORT', 'Administrador/Suporte')], default='STUDENT', max_length=20, verbose_name='Perfil')),
                ('avatar', models.ImageField(blank=True, help_text='Foto do perfil (opcional)', null=True, upload_to='avatars/%Y/%m/', verbose_name='Foto de Perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Sigla do Estado (ex: SP, RJ)', max_length=2, verbose_name='UF')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Endereço Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
