# Generated by Django 4.2.27 on 2026-01-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_instructorprofile_address_neighborhood_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_city',
            field=models.ForeignKey(blank=True, help_text='Cidade onde o aluno busca instrutores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='marketplace.city', verbose_name='Cidade Preferida'),
        ),
    ]
