# Generated by Django 4.2.27 on 2026-01-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_preferred_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento para validação', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF sem pontos ou traços (apenas números)', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
