# Generated by Django 4.2.27 on 2026-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_date_profile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Razão do bloqueio', verbose_name='Motivo do Bloqueio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email confirmado via token', verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_verified',
            field=models.BooleanField(default=False, help_text='Selfie + documento verificados', verbose_name='Identidade Verificada'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Usuário bloqueado por atividade suspeita', verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Telefone confirmado via SMS/WhatsApp', verbose_name='Telefone Verificado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='Score de 0-100 baseado em verificações e reputação', verbose_name='Score de Confiança'),
        ),
    ]
