# Generated by Django 4.2.27 on 2026-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_accept_privacy_profile_accept_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=True, help_text='Usuário informou se é aluno ou instrutor. False para novos usuários via Google.', verbose_name='Cadastro Completo'),
        ),
    ]
