# Generated by Django 4.2.27 on 2026-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_cpf_profile_unique_profile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_service_offers',
            field=models.BooleanField(default=True, help_text='Aluno aceita ser contactado por instrutores e auto-escolas com ofertas de serviços', verbose_name='Aceita Ofertas de Serviços'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accept_privacy',
            field=models.BooleanField(default=False, help_text='Confirmação de aceite da política de privacidade', verbose_name='Aceita Política de Privacidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accept_terms',
            field=models.BooleanField(default=False, help_text='Confirmação de aceite dos termos de uso', verbose_name='Aceita Termos de Uso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF sem pontos ou traços (apenas números)', max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Usuário informou se é aluno ou instrutor. False para novos usuários via Google.', verbose_name='Cadastro Completo'),
        ),
    ]
