# Generated by Django 4.2.27 on 2026-01-06 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, help_text='Usado se autor não estiver logado', max_length=100, verbose_name='Nome do Autor')),
                ('rating', models.PositiveIntegerField(help_text='1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Comentário')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicado'), ('PENDING', 'Pendente'), ('HIDDEN', 'Oculto')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Autor (usuário)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.instructorprofile', verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='reviews_rev_instruc_409ab6_idx'), models.Index(fields=['status', 'created_at'], name='reviews_rev_status_c24b9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Denunciante')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Denunciante')),
                ('reason', models.CharField(choices=[('FRAUD', 'Fraude/Documentos Falsos'), ('INAPPROPRIATE', 'Comportamento Inadequado'), ('SCAM', 'Golpe/Cobrança Indevida'), ('OTHER', 'Outro')], max_length=50, verbose_name='Motivo')),
                ('details', models.TextField(help_text='Descreva a situação', max_length=2000, verbose_name='Detalhes')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('INVESTIGATING', 'Em Investigação'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Observações da investigação', verbose_name='Notas do Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.instructorprofile', verbose_name='Instrutor')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante (usuário)')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='reviews_rep_instruc_b9f761_idx'), models.Index(fields=['status', 'created_at'], name='reviews_rep_status_597812_idx')],
            },
        ),
    ]
